fix : modify CD workflows and set port

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -114,9 +114,16 @@ jobs:
 
               # Health Check
               echo "Performing health check for GREEN"
-              until [ "$(curl -s -o /dev/null -w '%{http_code}' https://api.tigleisure.com/tig/health)" == "200" ]; do
+              MAX_RETRIES=10
+              RETRY_COUNT=0
+              until [ "$(curl -s -o /dev/null -w '%{http_code}' http://localhost:8082/tig/health)" == "200" ]; do
                 echo "Waiting for GREEN environment to be healthy..."
                 sleep 5
+                RETRY_COUNT=$((RETRY_COUNT + 1))
+                if [ "$RETRY_COUNT" -ge "$MAX_RETRIES" ]; then
+                  echo "Health check for GREEN environment failed after $MAX_RETRIES retries."
+                  exit 1
+                fi
               done
 
               # Nginx 설정 업데이트
@@ -137,9 +144,16 @@ jobs:
 
               # Health Check
               echo "Performing health check for BLUE"
-              until [ "$(curl -s -o /dev/null -w '%{http_code}' https://api.tigleisure.com/tig/health)" == "200" ]; do
+              MAX_RETRIES=10
+              RETRY_COUNT=0
+              until [ "$(curl -s -o /dev/null -w '%{http_code}' http://localhost:8081/tig/health)" == "200" ]; do
                 echo "Waiting for BLUE environment to be healthy..."
                 sleep 5
+                RETRY_COUNT=$((RETRY_COUNT + 1))
+                if [ "$RETRY_COUNT" -ge "$MAX_RETRIES" ]; then
+                  echo "Health check for BLUE environment failed after $MAX_RETRIES retries."
+                  exit 1
+                fi
               done
 
               # Nginx 설정 업데이트
